# Generated by Django 5.0.2 on 2024-03-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='usuario',
        ),
    ]
